__description__ = 'Python project manager'
__url__ = 'https://github.com/afaucon/python_project_manager'
__version__ = '0.0.1'
__author__ = 'Adrien Faucon'
__author_email__ = 'adrien.faucon@gmail.com'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2019 Adrien Faucon'
